/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Sep 22, 2010, 2:20:20 PM
 */

package siemconverter;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author 08mcs310
 */
public class login extends javax.swing.JFrame {
DBconnection consql = null;
ResultSet rs=null;
    /** Creates new form login */
    public login() {
        initComponents();
         consql = new DBconnection();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPane = new javax.swing.JPanel();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        login_username = new javax.swing.JTextField();
        login_password = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIEMConverter");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        LoginPane.setBackground(new java.awt.Color(255, 255, 255));
        LoginPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        UserNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNameLabel.setText("Username");

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordLabel.setText("Password");

        login_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        login_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_username.setBorder(null);

        login_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        login_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_password.setBorder(null);

        login_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        login_btn.setText("Sign in");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPaneLayout = new javax.swing.GroupLayout(LoginPane);
        LoginPane.setLayout(LoginPaneLayout);
        LoginPaneLayout.setHorizontalGroup(
            LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPaneLayout.createSequentialGroup()
                .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPaneLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(PasswordLabel))
                    .addGroup(LoginPaneLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_password)
                            .addComponent(login_username)
                            .addComponent(login_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
                    .addGroup(LoginPaneLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        LoginPaneLayout.setVerticalGroup(
            LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPaneLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(UserNameLabel)
                .addGap(18, 18, 18)
                .addComponent(login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_btn)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("SIEM Converter");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed

        String StaffNo = null,username = null;
        boolean tusername=true,twelcome=true,tpassword=true;
        String pass_word = login_password.getText();
        String users_name = login_username.getText();
        String query_username="SELECT USER_NAME FROM USERS";
        rs=consql.retrieve(query_username);
        try
        {
        while (rs.next())
        {
           username=rs.getString("USER_NAME").toString();
           
            
            if (users_name.equalsIgnoreCase(username))
            {
                tusername=true;
                String query_password="SELECT USER_PASSWORD FROM USERS ";
                rs=consql.retrieve(query_password);
                try
                {
                    while (rs.next())
                    {
                        String password=rs.getString("USER_PASSWORD").toString();

                        if (pass_word.equals(password))
                            {
                             twelcome=true;
                             JOptionPane.showMessageDialog(null,"Welcome "+username+" to SIEMConverter");
                             HOME myinterface = new HOME();
                             myinterface.setVisible(true);
                             this.setVisible(false);
                            }
                            else
                        {tpassword=false; }
                                             
                                                   
                    }
                }
                catch(SQLException w)
                {
                    JOptionPane.showMessageDialog(null,w.getMessage(),"OOPs",JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {tusername=false; }
           
            }
        
        }
        catch(SQLException w)
        {
            JOptionPane.showMessageDialog(null,w.getMessage(),"oops user exeption  ",JOptionPane.ERROR_MESSAGE);
        }
       /* String query12="INSERT INTO userslogin_log(username,staffnumber) VALUES ('"+username+"','"+StaffNo+"')";
        con.update(query12);
        String query13="INSERT INTO userlogin(user) VALUES ('"+username+"')";
        con.update(query13); */

        if (tusername==false)
        {
            JOptionPane.showMessageDialog(null, "INVALID USER","INVALID USER",JOptionPane.ERROR_MESSAGE);
        }
        if (tpassword==false)
        {
            JOptionPane.showMessageDialog(null, "WRONG PASSWORD","WRONG PASSWORD",JOptionPane.ERROR_MESSAGE);;
        }

        

    }//GEN-LAST:event_login_btnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPane;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JTextField login_username;
    // End of variables declaration//GEN-END:variables

}
