/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siemconverter;

import javax.swing.*;



/**
 *
 * @author mark.meli
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPane = new javax.swing.JPanel();
        BackGroundImage = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(630, 470));
        setResizable(false);

        BackGroundPane.setBackground(new java.awt.Color(0, 0, 51));
        BackGroundPane.setMinimumSize(new java.awt.Dimension(650, 430));
        BackGroundPane.setPreferredSize(new java.awt.Dimension(629, 469));
        BackGroundPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siemconverter/Assets/Splash.png"))); // NOI18N
        BackGroundPane.add(BackGroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 400));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLabel.setText("Loading...");
        BackGroundPane.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 220, 20));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0%");
        BackGroundPane.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 50, 20));
        BackGroundPane.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 421, 630, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPane, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep(100);
                sp.LoadingValue.setText(i +"%");
                
                if (i==10){
                    sp.LoadingLabel.setText("Turning On Modules.");
                }
                if (i==20){
                    sp.LoadingLabel.setText("Loading Modules");
                }
                if (i==50){
                    sp.LoadingLabel.setText("Connecting to Database");
                }
                if (i==70){
                    sp.LoadingLabel.setText("Connection Successful");
                }
                if (i==80){
                    sp.LoadingLabel.setText("Launching Application");
                }
                if (i==100){
                     login myinterface = new login();
                     myinterface.setVisible(true);
                     sp.setVisible(false);
                }
                sp.LoadingBar.setValue(i);
            
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundImage;
    private javax.swing.JPanel BackGroundPane;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    // End of variables declaration//GEN-END:variables
}
